s0 = (float(input ("Digite o valor de s0:", )))
v0 = (float(input ("Digite o valor de v0:", )))
t = (float(input ("Digite o valor de t:", )))
a = (float(input ("Digite o valor de a:", )))
s = (s0+v0*t+ (1/2)*a*t*t**2)
print("Resultado =", s)